name: Test Ambient Sound Processing

on:
  # To run manually
  workflow_dispatch:
  push: 
    branches:
      - turnoff-actions
      
  #schedule:
  #  - cron: '51 21 8 7 *'
    
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9.18'
#        cache: 'pip'
#        cache-dependency-path: ambient_sound_analysis/requirements_noise.txt

    - name: Install Python dependencies
      run: |
        pip install setuptools==71.0.4
        pip install orcasound_noise@git+https://github.com/orcasound/ambient-sound-analysis@ffmpeg-quiet

 

    








